Repository newrelic/newrelic-python-agent, pull requests merged in 2023-03, with the labels that each got.

#774 Exclude Merged PRs Mergify Actions
  .github/mergify.yml
Labels: ready-to-merge

#778 Errors inbox attributes and tests
  newrelic/api/time_trace.py
  newrelic/api/transaction.py
  newrelic/core/attribute.py
  newrelic/core/error_node.py
  newrelic/core/stats_engine.py
  newrelic/core/transaction_node.py
  tests/agent_features/test_attributes_in_action.py
  tests/agent_features/test_error_events.py
  tests/agent_unittests/test_harvest_loop.py
  tests/testing_support/validators/validate_error_trace_attributes.py
Labels: ready-to-merge

#783 Add GraphQL Introspection Setting
  newrelic/core/config.py
  newrelic/hooks/framework_graphql.py
  tests/framework_ariadne/test_application.py
  tests/framework_graphene/test_application.py
  tests/framework_graphql/test_application.py
  tests/framework_strawberry/test_application.py
Labels: tests-failing

#779 Reduce number of spans in django framework
  newrelic/hooks/framework_django.py
  tests/component_djangorestframework/test_application.py
  tests/framework_django/test_application.py
  tests/framework_django/test_asgi_application.py
Labels: tests-failing, ready-to-merge

#790 Fix Redis Instance Info
  newrelic/hooks/datastore_redis.py
  tests/datastore_redis/test_instance_info.py
Labels: ready-to-merge

#787 Guard GraphQL Settings Lookup
  newrelic/hooks/framework_graphql.py
  tests/framework_graphql/test_application.py
Labels: ready-to-merge

#785 Error Group Callback API
  newrelic/agent.py
  newrelic/api/settings.py
  newrelic/api/time_trace.py
  newrelic/core/config.py
  newrelic/core/stats_engine.py
  tests/agent_features/test_error_events.py
  tests/agent_features/test_error_group_callback.py
  tests/testing_support/fixtures.py
  tests/testing_support/validators/validate_error_trace_attributes.py
Labels: ready-to-merge

#789 User Tracking for Errors Inbox
  newrelic/agent.py
  newrelic/api/transaction.py
  tests/agent_features/test_attributes_in_action.py
Labels: ready-to-merge

#791 Errors Inbox Improvements
  newrelic/agent.py
  newrelic/api/settings.py
  newrelic/api/time_trace.py
  newrelic/api/transaction.py
  newrelic/core/attribute.py
  newrelic/core/config.py
  newrelic/core/error_node.py
  newrelic/core/stats_engine.py
  newrelic/core/transaction_node.py
  tests/agent_features/test_attributes_in_action.py
  tests/agent_features/test_error_events.py
  tests/agent_features/test_error_group_callback.py
  tests/agent_unittests/test_harvest_loop.py
  tests/testing_support/fixtures.py
  tests/testing_support/validators/validate_error_trace_attributes.py
Labels: ready-to-merge
